// Promotes hand-curated recipes into the offline bundle. Reads a curated JSON
// array (the recipes a human approved out of the generator's staging file),
// re-runs the full safety + integrity vetting, assigns stable ids, and rewrites
// src/data/generated-meals.js. This is the only step that touches shipped data.
//
// Usage:
//   npm run recipes:promote -- [flags]
//
// Flags:
//   --in PATH     curated input (default scripts/generated/curated-recipes.json)
//   --dry-run     validate and report; do not write the bundle file
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { DEFAULT_SETTINGS } from "../src/data/meals.js";
import { MEAL_DB } from "./lib/full-db.mjs";
import { GENERATED_MEALS } from "../src/data/generated-meals.js";
import { normalizeMeal, rejectReason, nameKey, ingredientSimilarity } from "./lib/recipe.mjs";

// A curated recipe whose ingredient set overlaps an existing same-type recipe
// by at least this much is flagged (not rejected) as a likely thin variation.
const SIMILARITY_WARN = 0.85;

const HERE = dirname(fileURLToPath(import.meta.url));
const TARGETS = DEFAULT_SETTINGS.targets;
const OUT_FILE = resolve(HERE, "../src/data/generated-meals.js");

const args = process.argv.slice(2);
const flag = (name, fallback) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : fallback;
};
const dryRun = args.includes("--dry-run");
const inPath = resolve(flag("--in", resolve(HERE, "generated/curated-recipes.json")));

let curated;
try {
  curated = JSON.parse(readFileSync(inPath, "utf8"));
} catch (err) {
  console.error(`Could not read curated file ${inPath}: ${err.message}`);
  process.exit(1);
}
if (!Array.isArray(curated)) {
  console.error(`Curated file must be a JSON array of recipes.`);
  process.exit(1);
}

// Names already in the bundle (core + previously promoted) are off-limits.
const existingNames = new Set(MEAL_DB.map((m) => nameKey(m.name)));
// Recipes we compare against for near-duplicate warnings — grows as we keep.
const compareAgainst = [...MEAL_DB];
// Continue the g-id sequence from whatever is already promoted.
let nextId = GENERATED_MEALS.reduce((max, m) => {
  const n = Number(String(m.id).replace(/^g/, ""));
  return Number.isFinite(n) ? Math.max(max, n) : max;
}, 0) + 1;

const kept = [];
const rejected = [];
const warnings = [];
for (const raw of curated) {
  const { _gap, id, ...rest } = raw; // drop provenance + any stale id
  const meal = normalizeMeal(rest, rest.type);
  const reason = rejectReason(meal, { targets: TARGETS, existingNames });
  if (reason) {
    rejected.push({ name: raw?.name || "(unnamed)", reason });
    continue;
  }
  // Surface (don't block) likely thin variations of an existing same-type meal.
  let nearest = null;
  for (const other of compareAgainst) {
    if (other.type !== meal.type) continue;
    const sim = ingredientSimilarity(meal, other);
    if (sim >= SIMILARITY_WARN && (!nearest || sim > nearest.sim)) nearest = { name: other.name, sim };
  }
  if (nearest) warnings.push({ name: meal.name, like: nearest.name, sim: nearest.sim });

  existingNames.add(nameKey(meal.name));
  const promoted = { id: `g${nextId++}`, ...meal };
  compareAgainst.push(promoted);
  kept.push(promoted);
}

console.log(`\n  Promote — ${curated.length} curated, ${kept.length} valid, ${rejected.length} rejected, ${warnings.length} flagged.`);
for (const r of rejected) console.log(`    ✗ ${r.name}: ${r.reason}`);
for (const w of warnings) console.log(`    ⚠ ${w.name}: ${Math.round(w.sim * 100)}% ingredient overlap with "${w.like}" — review for duplication`);

if (!kept.length) {
  console.log("\n  Nothing valid to promote. No changes written.\n");
  process.exit(rejected.length ? 1 : 0);
}

const merged = [...GENERATED_MEALS, ...kept];
const file = `// AUTO-GENERATED — curated AI recipes folded into the cookbook.
//
// Do not edit this file by hand. The pipeline owns it:
//   1. npm run recipes:generate   → staging file of AI candidates
//   2. review/edit, save approved ones to scripts/generated/curated-recipes.json
//   3. npm run recipes:promote     → validates and writes them here
//
// These are spread into MEAL_DB in meals.js, so they ship in the offline bundle
// and are subject to the same coverage + integrity tests as the core recipes.
export const GENERATED_MEALS = ${JSON.stringify(merged, null, 2)};
`;

if (dryRun) {
  console.log(`\n  Dry run — would write ${merged.length} generated recipes to ${OUT_FILE}.\n`);
} else {
  writeFileSync(OUT_FILE, file);
  console.log(`\n  Wrote ${merged.length} generated recipes to src/data/generated-meals.js.`);
  console.log(`  Run \`npm test\` to confirm coverage + integrity still pass, then commit.\n`);
}
